[ZEUS-4591] Fix video playing in background when switching
StreamAMG/playback-sdk-ios pull request #23
Opened 2024-07-10 13:34 UTC by artem-y-pamediagroup

## Jira
- ZEUS-4591
- part of the fix for SE-973, SE-1032
## Changes
- fixed removal of action handler targets from `MPRemoteCommandCenter`, which were capturing an instance of the player
- got rid of the reference to SwiftUI view in the `BitmovinPlayerPlugin`, used a weak reference to the player itself, in order to make the lifecycle of SwiftUI view and its dependencies predictable
- for this, added a new init for the `BitMovinPlayerView` to enable passing the player from outside of the view
- added creation and assignment of the `uiConfig` into the `setup` method of the plugin, so when the player is created outside it's also set up properly
- inside `PlaybackUIView`, put the state updates onto the main queue

2024-07-10 14:54 UTC, KharchenkoAlex approved these changes

2024-07-11 08:57 UTC, zachtom requested changes

2024-07-11 08:57 UTC, zachtom commented on Sources/PlaybackSDK/PlayBackSDKManager.swift
> +    public func loadHLSStream(forEntryId entryId: String, andAuthorizationToken: String?, completion: @escaping (Result<URL, PlayBackAPIError>) -> Void) {
Any reason for making this public? Wondering why this was internal before.

2024-07-11 08:57 UTC, zachtom commented on Sources/PlaybackSDK/Player Plugin/BitMovinPlugin/BitMovinPlayerView.swift
> +    public init(hlsURLString: String, player: Player, title: String) {
As discussed can we add some comments to these methods?

2024-07-12 08:20 UTC, zachtom approved these changes

2024-07-12 08:41 UTC, merged